name: Build and Deploy

on:
  push:
    branches:
      - main  # 触发分支，根据需要修改

jobs:
  build:
    runs-on: ubuntu-latest  # 或者使用其他需要的运行环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # 使用你需要的 Node.js 版本
        cache: 'pnpm'

    - name: Install pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 8  # 使用你需要的 pnpm 版本，例如 6 或最新版本
        run_install: false  # 先不运行 install，稍后手动执行

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    - name: Setup pnpm cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
    - name: Install dependencies
      run: pnpm install --frozen-lockfile  # 使用 --frozen-lockfile 以确保依赖的一致性

    - name: Build project
      run: pnpm run build  # 替换为你的构建命令，例如 pnpm run build 或其他自定义脚本
